---
title: "Transformation Notes"
author: "Eric Desoiza"
header-includes:
   - \usepackage{amsthm, amssymb,latexsym, amsmath}
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 4.1 Inverse Transform Method

Suppose we want to generate the value of a discrete random variable X. To accomplish this, we generate a random number U which is uniformly distributed over (0,1)

After generating a random number U, we determine the value of X by finding the interval of $[F(x_i), F(X_j)]$ in which U lies or by finding the inverse F(U). It is for this reason that the above is called the discrete inverse transform method for generating X.

Another way to generate a random permutation is to generate n random uniform variable and then use the indices of the successive values as the random permutation. 

# 4.2 Generating a Poisson Random Variable 

The key to using the inverse transform method to generate usch a random variable is the following identity:

$$p_{i+1} = \frac{\lambda}{i + 1} p_i, \quad i \geq 0$$

Upon using the above recursion to compute the Poisson probabilities as they become needed, the inverse transform algorithm is as follows

1) Generate U
2) i = 0, p = $e^{-\lambda}$, F = p.
3) If U < F, set X = i and stop.
4) p = $\lambda p / (i+1)$, F = F + p, i = i + 1.
5) Go to Step 3.

This above algorithm successively generates from 0 to 1 to 2 and on. 

# 5.1 Inverse Transform Algorithm

Let U be a uniform (0,1) random variable. For any continuous distribution function F the random variable X defined by 

$$X = F^{-1}(U)$$

has distribution F.

# 5.2 Rejection Method

We can use an arbitrary density function g(x) to assist in sampling f(x) by establish some probability proportional to f(Y)/g(Y).

Let c be a constant such that

$$\frac{f(y)}{g(y)} \leq c \quad \textrm{for all y}$$

1) Generate Y having density g
2) Generate a random number U
3) If $U \leq \frac{f(Y)}{cg(Y)}$, set X = Y. Otherwise, return to Step 1

This process is the exact same as the discrete process except the density has replaced the mass function

i) The random variable generated by the rejection method has density f
ii) The number of iterations of the algorithm that are needed is a geometric random variable with mean c



